# Лабораторна робота №1 з глибинного навчання студента групи Ім-22 Овсюка Юрія

In [1]:
import numpy as np
from numpy.linalg import norm

In [2]:
def distance_print(distance_mat, eq_num):
    
    val = distance_mat[~np.eye(distance_mat.shape[0],dtype=bool)].min()
    bool_arr = distance_mat == val
    idx = []
    for i in range(bool_arr.shape[0]):
        for j in range(bool_arr.shape[1]):
            if i == j:
                continue
            else:
                if bool_arr[i][j] == True:
                    idx.append([i, j])
    print(f"Для формули {eq_num} відстані: \n")
    print(distance_mat) 
    print('\n' + "Найменшим елементом є " + str(val) + '\n')
    print('Йому відповідають шаблони: ', end=' ')
    for val in idx:
        print(str(val[0]+1) + " та " + str(val[1]+1), end='; ')
    print('\n')

# 2.1 Індивідуальні завдання першого блоку

## 3.1

In [3]:
def L_2(s, x):
    return np.sqrt(np.sum((s-x)**2))

def L_3(s, x, lambd):
    return (np.sum((s-x)**(lambd)))**(1/lambd)

def L_4(s, x):
    return np.sum(np.abs(s-x))

def L_5(s, x, eta):
    return np.sqrt(eta @ ((s-x)**2).T)

def L_6(s, x, lambd, eta):
    return (eta @ ((s-x)**lambd).T)**(1/lambd)

def L_7(s, x, eta):
    return eta @ (np.abs(s-x)).T

def L_8(s, x):
    return np.sum(np.abs(s-x)/np.abs(s+x))

def L_9(s, x):
    n = x.shape[0]
    summa = 0
    for q in range(0, n-1):
        for k in range(1, n):
            if k>q:
                summa += np.sign(s[q]-s[k]) * np.sign(x[q]-x[k])
    return 1 - (2/(n*(n-1))) * summa

def L_10(s, x):
    return np.max(np.abs(s-x))

## 3.2

### Зчитати з файлу

In [13]:
name_of_matrix = "first_block_X.txt"
name_of_weights = "first_block_weights.txt"

X = np.loadtxt(name_of_matrix, delimiter=',')
eta_of_weights = np.loadtxt(name_of_weights, delimiter=',')
n = X.shape[0]
m = X.shape[1]

### Згенерувати випадковим чином

In [4]:
n = 5
m = 6
X = np.random.sample((n,m))
eta = np.random.sample(m)

### Ініціалізуємо матриці відстаней та виводимо зчитані дані

In [14]:
lamd = 4
L_2_distances = np.zeros((n,n))
L_3_distances = np.zeros((n,n))
L_4_distances = np.zeros((n,n))
L_5_distances = np.zeros((n,n))
L_6_distances = np.zeros((n,n))
L_7_distances = np.zeros((n,n))
L_8_distances = np.zeros((n,n))
L_9_distances = np.zeros((n,n))
L_10_distances = np.zeros((n,n))

print("Матриця шаблонів :")
print("\n")
print(X)
print("\n")
print("Матриця вагових коефіцієнтів: ")
print("\n")
print(eta)

Матриця шаблонів :


[[0.82141972 0.04642155 0.64588296 0.59955833 0.54348868 0.41846437]
 [0.88574574 0.31988043 0.6388927  0.17943034 0.88372288 0.01598445]
 [0.3462443  0.7624472  0.31300019 0.96322643 0.79033617 0.12397609]
 [0.7063229  0.5163329  0.65039904 0.33653938 0.98784613 0.326713  ]
 [0.95537726 0.73712664 0.22150833 0.0243943  0.05667627 0.6166563 ]]


Матриця вагових коефіцієнтів: 


[0.97881025 0.33173321 0.91515194 0.92442063 0.45940727 0.92583844]


In [ ]:
for i in range(n):
    for j in range(n):
        L_2_distances[i][j] = L_2(X[i], X[j]) 
        L_3_distances[i][j] = L_3(X[i], X[j], lambd=lamd)
        L_4_distances[i][j] = L_4(X[i], X[j])
        L_5_distances[i][j] = L_5(X[i], X[j], eta=eta)
        L_6_distances[i][j] = L_6(X[i], X[j], lambd=lamd, eta=eta)
        L_7_distances[i][j] = L_7(X[i], X[j], eta=eta)
        L_8_distances[i][j] = L_8(X[i], X[j])
        L_9_distances[i][j] = L_9(X[i], X[j])
        L_10_distances[i][j] = L_10(X[i], X[j])

In [ ]:
distance_print(L_2_distances, 2)
distance_print(L_3_distances, 3)
distance_print(L_4_distances, 4)
distance_print(L_5_distances, 5)
distance_print(L_6_distances, 6)
distance_print(L_7_distances, 7)
distance_print(L_8_distances, 8)
distance_print(L_9_distances, 9)
distance_print(L_10_distances, 10)

## 3.3

In [ ]:
patt_weighted_1 = np.array([240, 310, 58, 170, 90])
patt_weighted_2 = np.array([0.35, 270, 0.47, 160, 0.89])

eta_weighted = np.array([120, 1.2, 150, 1.4, 100])

ans_simp_2 = L_2(patt_weighted_1, patt_weighted_2)
ans_simp_3 = L_3(patt_weighted_1, patt_weighted_2, 4)
ans_simp_4 = L_4(patt_weighted_1, patt_weighted_2)

ans_weighted_5 = L_5(patt_weighted_1, patt_weighted_2, eta=eta_weighted)
ans_weighted_6 = L_6(patt_weighted_1, patt_weighted_2, lambd=4, eta=eta_weighted)
ans_weighted_7 = L_7(patt_weighted_1, patt_weighted_2, eta=eta_weighted)

print("Проста евклідова відстань дорівнює " + str(ans_simp_2))
print("Зважена евклідова відстань дорівнює " + str(ans_weighted_5))
print("Проста відстань мінковського дорівнює " + str(ans_simp_3))
print("Зважена відстань мінковсього дорівнює " + str(ans_weighted_6))
print("Проста city block відстань дорівнює " + str(ans_simp_4))
print("Зважена city block відстань дорівнює " + str(ans_weighted_7))

## 3.4

In [ ]:
patt_kend_1 = np.array([0.69565198, 0.31632395, 0.63817466, 0.68009122, 0.60589068, 0.03026583])
patt_kend_2 = np.array([0.87359942, 0.46275467, 0.65897428, 0.6597006,  0.50686113, 0.18992137])

ans_kend_1_2 = L_9(patt_kend_1, patt_kend_2)
print("Відстань по Кендалу дорівнює " + str(ans_kend_1_2) + ". Тут воно мінімальне, оскільки розташування елементів однотипне")

In [ ]:
patt_kend_3 = np.array([0.42142548, 0.30893455, 0.74811409, 0.88521356, 0.86045849, 0.36840119])
patt_kend_4 = np.array([0.83954871, 0.99893566, 0.79575212, 0.2373569,  0.48252239, 0.94160838])

ans_kend_3_4 = L_9(patt_kend_3, patt_kend_4)
print("Відстань по Кендалу дорівнює " + str(ans_kend_3_4) + ". Тут воно максимальне, оскільки розташування елементів різнобічне")

## 3.5

In [ ]:
patt_chebish_1 = np.array([50.28, 19.16, 22.05, 37.36, 15.11])
patt_chebish_2 = np.array([49.28, 19.13, 22.34, 37.17, 15.11])

ans_chebishev_1_2 = L_10(patt_chebish_1, patt_chebish_2)
print("Відстань по Чебишеву дорівнює " + str(ans_chebishev_1_2) + ", що має відповідати моєму номеру в журналі"

## 3.6

In [ ]:
patt_cheb_kend_1 = np.array([0.86, 0.77, 0.18, 0.48, 0.7633333333333334, 0.92], dtype='float64')
patt_cheb_kend_2 = np.array([0.65, 0.12, 0.65, 0.68, 0.03, 0.94], dtype='float64')

ans_kend = L_9(patt_cheb_kend_1, patt_cheb_kend_2)
ans_cheb = L_10(patt_cheb_kend_1, patt_cheb_kend_2)
print("Відстань по Кендалу дорівнює " + str(ans_kend))
print("Відстань по Чебишеву дорівнює " + str(ans_cheb))

# 2.2 Індивідуальні завдання другого блоку

## 3.1

In [21]:
def _a(patt_i, patt_j):
    return patt_j @ patt_i.T

def _b(patt_i, patt_j):
    return (1-patt_j) @ (1-patt_i).T

def _g(patt_i, patt_j):
    return patt_i @ (1-patt_j).T

def _h(patt_i, patt_j):
    return (1-patt_i) @ patt_j.T

def S_1(X_i, X_j):
    a = _a(X_i, X_j)
    b = _b(X_i, X_j)
    g = _g(X_i, X_j)
    h = _h(X_i, X_j)
    n = a + b + g + h

    return a/n

def S_2(X_i, X_j):
    a = _a(X_i, X_j)
    b = _b(X_i, X_j)
    g = _g(X_i, X_j)
    h = _h(X_i, X_j)
    
    return a/(a+g+h)

def S_3(X_i, X_j):
    a = _a(X_i, X_j)
    g = _g(X_i, X_j)
    h = _h(X_i, X_j)
    
    return a/(2*a+g+h)

def S_4(X_i, X_j):
    a = _a(X_i, X_j)
    g = _g(X_i, X_j)
    h = _h(X_i, X_j)
    
    return a/(a+2*(g+h))

def S_5(X_i, X_j):
    a = _a(X_i, X_j)
    b = _b(X_i, X_j)
    g = _g(X_i, X_j)
    h = _h(X_i, X_j)
    n = a + b + g + h
    
    return (a+b)/n

def S_6(X_i, X_j):
    a = _a(X_i, X_j)
    g = _g(X_i, X_j)
    h = _h(X_i, X_j)
    
    return a/(g+h)

def S_7(X_i, X_j):
    a = _a(X_i, X_j)
    b = _b(X_i, X_j)
    g = _g(X_i, X_j)
    h = _h(X_i, X_j)
    
    return (a*b-g*h)/(a*b+g*h)

def mean_euclid(X_i, X_j): # завдання 3.3 індивідуального блоку. Протестуємо серендню Евклідову відстань  
    a = _a(X_i, X_j)
    b = _b(X_i, X_j)
    g = _g(X_i, X_j)
    h = _h(X_i, X_j)
    n = a + b + g + h
    
    return np.sqrt((g+h)/n)

def hamming(X_i, X_j): # завдання 3.5 індивідуального блоку. Протестуємо відстань Хеммінга
    g = _g(X_i, X_j)
    h = _h(X_i, X_j)
    
    return g+h


## 3.2

### Зчитування з файлів

In [36]:
name_of_matrix_2 = "second_block_X_2.txt"

X_2 = np.loadtxt(name_of_matrix_2, delimiter=',', dtype=None)

n = X_2.shape[0]
m = X_2.shape[1]

### Генерація випадковим чином

In [33]:
n = 5
m = 4
X_2 = np.random.binomial(1, 0.5, size=(n,m))

### Ініціалізуємо матрицю відстаней та виводимо дані

In [37]:
S_1_distances = np.zeros((n,n))
S_2_distances = np.zeros((n,n))
S_3_distances = np.zeros((n,n))
S_4_distances = np.zeros((n,n))
S_5_distances = np.zeros((n,n))
S_6_distances = np.zeros((n,n))
S_7_distances = np.zeros((n,n))
mean_euclid_distances = np.zeros((n,n)) # завдання 3.3
hamming_distances = np.zeros((n,n)) # завдання 3.5

print("Матриця шаблонів: ")
print("\n")
print(X_2)

Матриця шаблонів: 


[[1. 0. 1. 1.]
 [0. 1. 1. 1.]
 [0. 1. 0. 1.]
 [1. 0. 0. 1.]
 [0. 1. 0. 0.]]


In [38]:
for i in range(n):
    for j in range(n):
        S_1_distances[i][j] = S_1(X_2[i], X_2[j]) 
        S_2_distances[i][j] = S_2(X_2[i], X_2[j])
        S_3_distances[i][j] = S_3(X_2[i], X_2[j])
        S_4_distances[i][j] = S_4(X_2[i], X_2[j])
        S_5_distances[i][j] = S_5(X_2[i], X_2[j])
        S_6_distances[i][j] = S_6(X_2[i], X_2[j])
        S_7_distances[i][j] = S_7(X_2[i], X_2[j])

C:\Users\Andrii\AppData\Local\Temp\ipykernel_5292\787013973.py:58: RuntimeWarning: divide by zero encountered in double_scalars
  return a/(g+h)


In [39]:
distance_print(S_1_distances, 1)
distance_print(S_2_distances, 2)
distance_print(S_3_distances, 3)
distance_print(S_4_distances, 4)
distance_print(S_5_distances, 5)
distance_print(S_6_distances, 6)
distance_print(S_7_distances, 7)

Для формули 1 відстані: 

[[0.75 0.5  0.25 0.5  0.  ]
 [0.5  0.75 0.5  0.25 0.25]
 [0.25 0.5  0.5  0.25 0.25]
 [0.5  0.25 0.25 0.5  0.  ]
 [0.   0.25 0.25 0.   0.25]]

Найменшим елементом є 0.0

Йому відповідають шаблони:  1 та 5; 4 та 5; 5 та 1; 5 та 4; 

Для формули 2 відстані: 

[[1.         0.5        0.25       0.66666667 0.        ]
 [0.5        1.         0.66666667 0.25       0.33333333]
 [0.25       0.66666667 1.         0.33333333 0.5       ]
 [0.66666667 0.25       0.33333333 1.         0.        ]
 [0.         0.33333333 0.5        0.         1.        ]]

Найменшим елементом є 0.0

Йому відповідають шаблони:  1 та 5; 4 та 5; 5 та 1; 5 та 4; 

Для формули 3 відстані: 

[[0.5        0.33333333 0.2        0.4        0.        ]
 [0.33333333 0.5        0.4        0.2        0.25      ]
 [0.2        0.4        0.5        0.25       0.33333333]
 [0.4        0.2        0.25       0.5        0.        ]
 [0.         0.25       0.33333333 0.         0.5       ]]

Найменшим елементо

## 3.3 

In [ ]:
mean_euclid_distances = np.zeros((n,n)) # завдання 3.3
for i in range(n):
    for j in range(n):
        mean_euclid_distances[i][j] = mean_euclid(X_2[i], X_2[j]) 

distance_print(mean_euclid_distances, "середньої евклідової відстані") # завдання 3.3

## 3.4

In [ ]:
patt_01 = np.array([1, 1, 1, 1, 1, 1])
patt_02 = np.array([1, 1, 1, 1, 1, 1])

ans_00 = S_2(patt_01, patt_02)

print("Для ф-ції Жокара та Нідмена отримуємо макс. значення, а саме " + str(ans_00) + ", оскільки усі значення співпадають")

In [ ]:
patt_03 = np.array([1, 0, 1, 0, 1, 0])
patt_04 = np.array([0, 1, 0, 1, 0, 1])

ans_034 = S_2(patt_03, patt_04)

print("Для ф-ції Жокара та Нідмена отримуємо мін. значення, а саме " + str(ans_034) + ", оскільки усі значення різні")

## 3.5

In [ ]:
for i in range(n):
    for j in range(n):
        hamming_distances[i][j] = hamming(X_2[i], X_2[j]) # завдання 3.5
        
distance_print(hamming_distances, "хемінга")

In [ ]:
pat_1 = np.array([1, 0, 0, 0, 0])
pat_2 = np.array([0, 0, 0, 0, 0])

ans_1 = hamming(pat_1, pat_2)
print("Відстань Хемінга дає значення " + str(ans_1))

## 3.6

In [ ]:
pat_3 = np.array([0, 0, 0, 1])
pat_4 = np.array([0, 0, 1, 1])

ans_2 = S_6(pat_3, pat_4)
print("Використовуючи ф-цію збіжності Кульжинського, отримуємо для заданих шаблонів значення " + str(ans_2) + ", що дорівнює значенню із завдання 3.5")

# 2.3 Індивідуальні завдання третього блоку

## 3.1

In [43]:
def L_cosine(S_i, X_j):
    return np.arccos(S_i @ X_j.T/(np.linalg.norm(S_i) * np.linalg.norm(X_j))) * 180 / np.pi 

def L_scal_prod(S_i, X_j):
    return S_i @ X_j.T

## 3.2, 3.3 та 3.4

### Зчитування з файлів

In [48]:
name_of_matrix_3 = "third_block_X_3.txt"
name_of_radius = "third_block_radius.txt"
name_of_angles = "third_block_angles.txt"

X_3 = np.loadtxt(name_of_matrix_3, delimiter=',')
phi = np.loadtxt(name_of_radius, delimiter=',')
R = np.loadtxt(name_of_angles, delimiter=',')

n = X_3.shape[0]
m = X_3.shape[1]

### Генерація випадковим чином

In [40]:
n = 5
m = 6
phi = np.random.uniform(low=40, high=120, size=(n,1))
R = np.random.randint(low=8, high=50, size=(n,1))
X_3 = np.random.sample((n,m))

### Ініціалізуємо матриці відстаней та виводимо дані

In [49]:
L_cosine_distances = np.zeros((n,n))
L_scal_prod_distances = np.zeros((n,n))
membership_cosine = np.chararray((n,n))
membership_scal_prod = np.chararray((n,n))
membership_euclidian = np.chararray((n,n))

print("Матриця шаблонів: \n")
print(X_3)
print('\n')
print("Матриця радіусів: \n")
print(R)
print('\n')
print("Матриця кутів: \n")
print(phi)

Матриця шаблонів: 

[[0.16929655 0.0414269  0.76195633 0.30749919 0.72768514 0.09767102]
 [0.75315215 0.47395202 0.19392633 0.75596718 0.77059016 0.06592258]
 [0.67492733 0.28363842 0.67880563 0.21884121 0.22739774 0.7784144 ]
 [0.98894383 0.98567329 0.98111237 0.73114229 0.03517814 0.07551569]
 [0.96617323 0.43572117 0.57058564 0.49837474 0.36005359 0.59880235]]


Матриця радіусів: 

[ 62.84020852 100.99877451  49.52935589  56.5693716   58.42845148]


Матриця кутів: 

[43. 17. 29. 45. 37.]


In [50]:
for i in range(n):
    for j in range(n):
        L_cosine_distances[i][j] = L_cosine(X_3[i], X_3[j]) 
        L_scal_prod_distances[i][j] = L_scal_prod(X_3[i], X_3[j])
        membership_cosine[i][j] = "Y" if L_cosine(X_3[i], X_3[j]) < phi[i] else "N"
        membership_scal_prod[i][j] = "Y" if L_scal_prod(X_3[i], X_3[j]) < R[i] else "N"
        membership_euclidian[i][j] = "Y" if L_2(X_3[i], X_3[j]) < R[i] else "N"

C:\Users\Andrii\AppData\Local\Temp\ipykernel_5292\1400432034.py:2: RuntimeWarning: invalid value encountered in arccos
  return np.arccos(S_i @ X_j.T/(np.linalg.norm(S_i) * np.linalg.norm(X_j))) * 180 / np.pi


In [51]:
distance_print(L_cosine_distances, 1)
distance_print(L_scal_prod_distances, 3)

Для формули 1 відстані: 

[[           nan 4.60593068e+01 4.91509130e+01 5.41705541e+01
  4.86251339e+01]
 [4.60593068e+01 8.53773646e-07 5.07821817e+01 4.08673765e+01
  3.37223689e+01]
 [4.91509130e+01 5.07821817e+01 8.53773646e-07 4.06429587e+01
  1.93323869e+01]
 [5.41705541e+01 4.08673765e+01 4.06429587e+01            nan
  3.05061703e+01]
 [4.86251339e+01 3.37223689e+01 1.93323869e+01 3.05061703e+01
  0.00000000e+00]]

Найменшим елементом є 19.33238690850327

Йому відповідають шаблони:  3 та 5; 5 та 3; 

Для формули 3 відстані: 

[[1.244576   1.09454885 0.95202936 1.21362291 1.09012282]
 [1.09454885 1.99911746 1.16637458 1.98705623 1.73852125]
 [0.95202936 1.16637458 1.70228492 1.83981063 1.8200574 ]
 [1.21362291 1.98705623 1.83981063 3.45365239 2.36704624]
 [1.09012282 1.73852125 1.8200574  2.36704624 2.18549184]]

Найменшим елементом є 0.9520293550612389

Йому відповідають шаблони:  1 та 3; 3 та 1; 



In [52]:
print("Приналежність за кутовою відстанню\n")
print(membership_cosine)
print('\nПриналежність за скалярним добутком\n')
print(membership_scal_prod)
print('\nПриналежність за евклідовою відстанню\n')
print(membership_euclidian)

Приналежність за кутовою відстанню

[[b'N' b'N' b'N' b'N' b'N']
 [b'N' b'Y' b'N' b'N' b'N']
 [b'N' b'N' b'Y' b'N' b'Y']
 [b'N' b'Y' b'Y' b'N' b'Y']
 [b'N' b'Y' b'Y' b'Y' b'Y']]

Приналежність за скалярним добутком

[[b'Y' b'Y' b'Y' b'Y' b'Y']
 [b'Y' b'Y' b'Y' b'Y' b'Y']
 [b'Y' b'Y' b'Y' b'Y' b'Y']
 [b'Y' b'Y' b'Y' b'Y' b'Y']
 [b'Y' b'Y' b'Y' b'Y' b'Y']]

Приналежність за евклідовою відстанню

[[b'Y' b'Y' b'Y' b'Y' b'Y']
 [b'Y' b'Y' b'Y' b'Y' b'Y']
 [b'Y' b'Y' b'Y' b'Y' b'Y']
 [b'Y' b'Y' b'Y' b'Y' b'Y']
 [b'Y' b'Y' b'Y' b'Y' b'Y']]
